### ISSUE TITLE
Cyclomatic Complexity value from resharper is different compare to other evaluator

### ISSUE THREAD

**Issue by Nness** [JetBrains/resharper-cyclomatic-complexity#3]
``` C#
private static IEnumerable<Result> Update(IEnumerable<Config> configs, Req req)
{
    foreach(Config config in configs) {
        config.Setting1 = req.Setting1 ?? config.Setting1;
        config.Setting2 = config.Setting1 || (req.Setting2 ?? config.Setting2);
        config.Setting3 = req.Setting3 ?? config.Setting3;
        config.Setting4 = req.Setting4 ?? config.Setting4;
        config.Setting5 = req.Setting5 ?? config.Setting5;
        config.Setting6 = req.Setting6 ?? config.Setting6;

        if(req.performAction != true) {
         continue;
        }

        PerformAction(config);
        yield return new Result {
            Id = config.Id,
            Text = config.Text
        };
    }
}
```

Above method result as 24 cyclomatic complexity from this resharper plugin, while visual studio's analysis only shows complexity of `1`. CodeMaid shows complexity of `1` as well.

I'm not sure which one did wrong, but its hard to manage project when every tools given different result while point out to article says it should keep at certain level.

**Comment by citizenmatt** [comment]
I don't think 1 is right - the `??` are conditional operators, and introduce branches into the code, so it should be equivalent to writing

``` csharp
if (req.Setting1 != null)
  config.Setting1 = req.Setting1;
else
  config.Setting1 = config.Setting1;
```

which would have a complexity of 2.

Even the `if` statement by itself would give you a complexity of 2, so I don't get where 1 is coming from.

**Comment by citizenmatt** [comment]
Actually, could you expand that code snippet a bit more, please? What do `Config` and `Req` look like?

**Comment by Nness** [comment]
`config.Setting{num}` those are `Boolean`. While `req.Setting{num}` are `Nullable<Boolean>`. The idea is only when request have that field present, we modify the config, else use default.

If I'm going to have a method to decide what to use like following

```
bool Choose(bool? req, bool exist) {
     return req ?? exist;
}
```

Then the Cyclomatic complexity will drop. But what's the point? I can still type wrong like `Choose(req.Setting2, config.Setting1)`. Does this point actually make assign value more logical and less likely to go wrong? No.

I think that's probably one of reason why visual studio's Cyclomatic complexity just ignore it.

**Comment by Nness** [comment]
This ticket was while ago, finally found out where it originally come from. The action was actually relate to one of code I wrote for bulk setting change for contact configs. Action perform was for recreate token. While yield return was only performed if token been recreated.

I was using codemaid to diagnose CC value, that indicate as  1 or something, at some stage, I upgraded VS and codemaid had issue, and I found out codemaid actually using VS's CC value. Or they have same logic.

While when I check out resharper's value, it was huge all over the place. 

Surely I don't know a lot of actual CC calculation, but when one platform indicate 1 and the other indicate 24, there are something hugely wrong. Especially both of them saying it should keep under 10. 

Does above code complex? From my point of view its not, if intentionally make it low, it might become even more hard to read. The idea of the method is simple, go through set of configs, if request has indicate a specific setting need to be changed, we change it.  That's it. Maybe 1 feels wrong, but 24 doesn't seems correct either. 

If you take inner part out to another method, that method will have very high CC value too. The only way to decrease resharper's CC value is to make each assign value code to its own method.

**Comment by citizenmatt** [comment]
Confirming that it's boolean is very useful thanks. I think there are a couple of issues going on.

Firstly, as I stated above, I'm sure VS (and therefore Codemaid) are getting it wrong, as the `??` operators are conditional branches - if the first expression is `null`, the second expression isn't evaluated, and this could be a method call, etc. This is the same as an `if`, introducing a branch, and increasing complexity by 1. Adding multiple `??` operators adds extra routes through the code, increasing the complexity.

But, the ReSharper plugin is also getting it wrong, because of those boolean values - it shouldn't be that high. The problem is down to how ReSharper builds its control flow graph, which is uses to find redundant code and track data flow for e.g. possible `null` references, etc. When it sees a boolean value, such as a parameter, variable or property, it treats it as a conditional, as if `true` or `false` could be used. But there is no conditional code there - no `if` statements, no ternary `… ? … : …` expressions, etc. I'm using this graph to calculate the complexity, and it provides all of the nodes and edges needed, except in this case, it adds an extra unnecessary edge.

I've just fixed this issue by removing duplicate edges from the graph - if it's joining the same nodes together, it's not a unique path through the code, so it's not a unique edge, and this reduces the complexity. So, given the same code snippet, with `bool` and `bool?` properties, the complexity is now 13. I'm going to try and find another analyser that can work with this code to see if it says the same.

(Also, apologies for the very slow initial reply - I didn't get an email about it, and only found it because I'm updating for the latest ReSharper)

**Comment by petec-scribestar** [comment]
I've counted the CC manually and I come up with a figure of 14. 
5 instances of ?? = 10,
1 instance of || combined with ?? = 3,
1 instance of if = 1
That's how many tests I think are required to give full path coverage

**Comment by citizenmatt** [comment]
Thanks Pete. That means it's now in the right ball park.

**Comment by sheitmann** [comment]
you can also use the code posted here for another test
https://youtrack.jetbrains.com/issue/RSPL-4445

**Comment by citizenmatt** [comment]
Perfectly timed, thanks!

**Comment by citizenmatt** [comment]
With the fix I've just put in place, this is no longer 34, but 10. It's highlighting another bug - the `!Visible` causes ReSharper to treat this as a condition. If these are commented out, I get a CC of 1. Progress!

**Comment by Nness** [comment]
Cool!

**Comment by citizenmatt** [comment]
Latest version for 2016.1 is now on the gallery, with fixes to reduce these CC values.
